"use client";
import React, { useState, useEffect } from 'react';
import { Trophy, Play, ArrowRight, Shield, Eye, Clock, AlertCircle, Video } from 'lucide-react';

// Single video configuration with responsive thumbnails - moved outside to prevent recreation
const videoData = {
  id: 'featured-video',
  title: "Exclusive Training Video - Transform Your Life",
  videoUrl: "https://ftp.arcdatum.com/uploads/a53693ac60512ddaa1b060a1b1de6166.mp4",
  youtubeId: "M4zQhkuRSdM",
  thumbnail: {
    mobile: "https://via.placeholder.com/360x640/000000/FFFFFF?text=Mobile+Thumbnail",
    desktop: "https://via.placeholder.com/1280x720/000000/FFFFFF?text=Desktop+Thumbnail",
    youtubeMobile: "https://img.youtube.com/vi/M4zQhkuRSdM/hqdefault.jpg",
    youtubeDesktop: "https://img.youtube.com/vi/M4zQhkuRSdM/maxresdefault.jpg"
  },
  duration: "Training Session",
  views: "Featured",
  category: "EXCLUSIVE TRAINING"
};

const Hero = () => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [matrixText, setMatrixText] = useState('');
  const [showFinalText, setShowFinalText] = useState(false);
  const [textContent, setTextContent] = useState({
    trophyText: "PROVEN SYSTEM • 10,000+ SUCCESS STORIES",
    welcomeText: "WELCOME TO",
    companyName: "ARCDATUM",
    description: "Join the exclusive mentorship program that's helped 1000+ students build profitable business, meet their fitness goals, have their credit repaired",
    stats: [
      { value: "$10M+", label: "Generated by Students" },
      { value: "10,000+", label: "Success Stories" },
      { value: "95%", label: "Success Rate" },
      { value: "24/7", label: "Support" }
    ]
  });

  // Matrix text scrambling effect
  useEffect(() => {
    const targetText = `${textContent.welcomeText}\n${textContent.companyName}`;
    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@#$%^&*()[]{}|;:,.<>?~`';
    let iterations = 0;
    const maxIterations = 60;
    
    const scrambleInterval = setInterval(() => {
      setMatrixText(targetText
        .split('')
        .map((char, index) => {
          if (char === '\n') return '\n';
          if (char === ' ') return ' ';
          
          if (iterations > index * 2) {
            return targetText[index];
          }
          
          return characters[Math.floor(Math.random() * characters.length)];
        })
        .join(''));
      
      iterations++;
      
      if (iterations >= maxIterations) {
        clearInterval(scrambleInterval);
        setShowFinalText(true);
      }
    }, 50);
    
    return () => clearInterval(scrambleInterval);
  }, [textContent.welcomeText, textContent.companyName]);

  // Fetch frontend text content from API
  useEffect(() => {
    const fetchTextContent = async () => {
      try {
        const response = await fetch('https://api.arcdatum.com/api/frontend/text/settings');
        if (!response.ok) {
          throw new Error(`Text API error! status: ${response.status}`);
        }
        const data = await response.json();
        
        // Update text content with API data, falling back to existing values if not available
        setTextContent(prev => ({
          trophyText: data.trophy_text || prev.trophyText,
          welcomeText: data.hero_section_banner_text || prev.welcomeText,
          companyName: "ARCDATUM", // Keeping this static as it's likely a brand name
          description: data.hero_section_description_text || prev.description,
          stats: data.hero_section_elements_text?.map((item, index) => ({
            value: item.element_heading || prev.stats[index]?.value || "",
            label: item.element_text || prev.stats[index]?.label || ""
          })) || prev.stats
        }));
      } catch (err) {
        console.error('Error fetching text content:', err);
        // Continue with existing text content if API fails
      } finally {
        setLoading(false);
      }
    };

    fetchTextContent();
  }, []);

  const handleVideoPlay = () => {
    setIsPlaying(true);
  };

  const handleVideoError = () => {
    setError("Unable to load video. Please try again later.");
  };

  // Matrix-style custom CSS
  const matrixStyles = `
    @import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700;900&family=Rajdhani:wght@300;400;500;600;700&family=Exo+2:wght@100;200;300;400;500;600;700;800;900&display=swap');
    
    .matrix-font-primary {
      font-family: 'Orbitron', 'Exo 2', monospace;
      letter-spacing: 0.1em;
    }
    
    .matrix-font-secondary {
      font-family: 'Rajdhani', 'Exo 2', sans-serif;
      letter-spacing: 0.05em;
    }
    
    .matrix-glow {
      text-shadow: 0 0 10px rgba(255, 255, 255, 0.5), 0 0 20px rgba(255, 255, 255, 0.3), 0 0 30px rgba(255, 255, 255, 0.1);
    }
    
    .matrix-green-glow {
      text-shadow: 0 0 10px #00ff41, 0 0 20px #00ff41, 0 0 40px #00ff41;
    }
    
    .matrix-text-effect {
      background: linear-gradient(45deg, #00ff41, #ffffff, #00ff41);
      background-size: 200% 200%;
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;
      animation: matrix-text-flow 3s ease-in-out infinite;
    }
    
    .matrix-scramble {
      font-family: 'Orbitron', 'Courier New', monospace;
      color: #00ff41;
      text-shadow: 0 0 10px #00ff41, 0 0 20px #00ff41, 0 0 40px #00ff41;
      animation: matrix-flicker 0.15s infinite linear;
    }
    
    .matrix-final-text {
      font-family: 'Orbitron', 'Exo 2', monospace;
      background: linear-gradient(45deg, #00ff41, #ffffff, #00ff41);
      background-size: 200% 200%;
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;
      animation: matrix-text-flow 3s ease-in-out infinite;
      text-shadow: 0 0 20px rgba(0, 255, 65, 0.5);
    }
    
    @keyframes matrix-text-flow {
      0%, 100% { 
        background-position: 0% 50%; 
      }
      50% { 
        background-position: 100% 50%; 
      }
    }
    
    @keyframes matrix-flicker {
      0%, 100% { 
        opacity: 1; 
      }
      50% { 
        opacity: 0.8; 
      }
    }
    
    .matrix-border {
      border: 1px solid #00ff41;
      box-shadow: 0 0 10px rgba(0, 255, 65, 0.3), inset 0 0 10px rgba(0, 255, 65, 0.1);
    }
  `;

  // Video Section Component (Responsive: portrait on mobile, landscape on desktop)
  const VideoSection = () => {
    // Initialize with proper thumbnail URL immediately to prevent flashing
    const getInitialThumbnail = () => {
      if (typeof window === 'undefined') {
        return videoData.thumbnail.youtubeDesktop; // SSR fallback
      }
      const mobile = window.innerWidth < 1024;
      if (videoData.youtubeId) {
        return mobile ? videoData.thumbnail.youtubeMobile : videoData.thumbnail.youtubeDesktop;
      }
      return mobile ? videoData.thumbnail.mobile : videoData.thumbnail.desktop;
    };

    const [isMobile, setIsMobile] = useState(() => typeof window !== 'undefined' ? window.innerWidth < 1024 : false);
    const [thumbnailUrl, setThumbnailUrl] = useState(getInitialThumbnail);

    // Detect screen size and set appropriate thumbnail
    useEffect(() => {
      const checkMobile = () => {
        const mobile = window.innerWidth < 1024;
        setIsMobile(mobile);
        
        // Use YouTube thumbnails if available, otherwise use fallback
        if (videoData.youtubeId) {
          setThumbnailUrl(mobile 
            ? videoData.thumbnail.youtubeMobile 
            : videoData.thumbnail.youtubeDesktop
          );
        } else {
          setThumbnailUrl(mobile 
            ? videoData.thumbnail.mobile 
            : videoData.thumbnail.desktop
          );
        }
      };
      
      // Only run on resize, initial state is already set
      window.addEventListener("resize", checkMobile);
      return () => window.removeEventListener("resize", checkMobile);
    }, []);

    return (
      <div className="w-full max-w-4xl mx-auto">
        <div className={`relative w-full ${isMobile ? "aspect-video max-w-full mx-auto" : "aspect-video"} group`}>
          {/* Video Container */}
          <div className="relative w-full h-full rounded-2xl overflow-hidden shadow-2xl shadow-black/50">
            {!isPlaying ? (
              <>
                {/* Thumbnail with Play Button Overlay */}
                <div className="relative w-full h-full bg-black">
                  {thumbnailUrl && (
                    <img
                      src={thumbnailUrl}
                      alt="Video Thumbnail"
                      className={`w-full h-full ${isMobile ? 'object-contain' : 'object-cover'}`}
                      loading="eager"
                      decoding="async"
                      onError={(e) => {
                        console.error('Thumbnail failed to load:', e);
                        // Fallback to placeholder if thumbnail fails
                        e.target.src = isMobile 
                          ? "https://via.placeholder.com/360x640/1a1a1a/ffffff?text=ARCDATUM+Training"
                          : "https://via.placeholder.com/1280x720/1a1a1a/ffffff?text=ARCDATUM+Training";
                      }}
                    />
                  )}
                  
                  {/* Play Button Overlay */}
                  <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-black/50 flex items-center justify-center">
                    <button
                      onClick={handleVideoPlay}
                      className="relative group-hover:scale-110 transition-transform duration-300"
                    >
                      <div className="w-20 h-20 md:w-24 md:h-24 bg-gradient-to-r from-yellow-400 to-orange-500 rounded-full flex items-center justify-center shadow-2xl shadow-black/50">
                        <div className="w-16 h-16 md:w-20 md:h-20 bg-black rounded-full flex items-center justify-center">
                          <Play className="w-8 h-8 md:w-10 md:h-10 text-yellow-400 ml-1" fill="currentColor" />
                        </div>
                      </div>
                    </button>
                  </div>
                  
                  {/* Video Info Overlay - Hidden on mobile */}
                  <div className="hidden md:block absolute bottom-0 left-0 right-0 p-4 md:p-6">
                    <div className="flex items-center justify-between mb-2">
                      <span className="px-3 py-1 bg-red-600 text-white text-xs md:text-sm font-bold rounded-full matrix-font-secondary">
                        {videoData.category}
                      </span>
                      <span className="px-3 py-1 bg-black/70 text-white text-xs md:text-sm rounded-full matrix-font-secondary">
                        {videoData.duration}
                      </span>
                    </div>
                    <h3 className="text-white text-lg md:text-xl font-bold matrix-font-primary line-clamp-2">
                      {videoData.title}
                    </h3>
                  </div>
                </div>
              </>
            ) : (
              /* YouTube Embed when playing */
              <div className="w-full h-full">
                <iframe
                  className="w-full h-full"
                  src={`https://www.youtube.com/embed/${videoData.youtubeId}?autoplay=1&rel=0&modestbranding=1`}
                  title="YouTube video player"
                  frameBorder="0"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                  allowFullScreen
                  loading="lazy"
                ></iframe>
              </div>
            )}
          </div>
        </div>
      </div>
    );
  };

  // Loading state
  if (loading) {
    return (
      <section id="hero" className="pt-24 pb-20 relative overflow-hidden min-h-screen flex items-center">
        <style>{matrixStyles}</style>
        <div className="container mx-auto px-6 relative z-10">
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            <div className="text-center lg:text-left">
              <h1 className="text-4xl md:text-6xl lg:text-7xl font-black mb-8 leading-tight matrix-font-primary">
                <span className="block text-white">Loading...</span>
              </h1>
            </div>
            <div className="flex items-center justify-center">
              <div className="animate-spin rounded-full h-32 w-32 border-b-2 border-yellow-400"></div>
            </div>
          </div>
        </div>
      </section>
    );
  }

  return (
    <section id="hero" className="pt-24 pb-20 relative overflow-hidden min-h-screen flex items-center">
      <style>{matrixStyles}</style>
      
      {/* Background Effects */}
      <div className="absolute inset-0">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-yellow-500/10 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-orange-500/10 rounded-full blur-3xl animate-pulse delay-1000"></div>
        <div className="absolute top-1/2 right-1/3 w-64 h-64 bg-red-500/5 rounded-full blur-2xl"></div>
      </div>

      <div className="container mx-auto px-6 relative z-10">
        {/* Mobile Layout - Video section first, then content */}
        <div className="block lg:hidden">
          <div className="space-y-16">
            {/* Video Section - First on Mobile */}
            <VideoSection />
            
            {/* Main Content - Second on Mobile */}
            <div className="text-center">
              <div className="inline-flex items-center gap-2 bg-gradient-to-r from-yellow-400/20 to-orange-500/20 border border-yellow-400/30 px-6 py-2 rounded-full text-yellow-400 mb-8 matrix-border">
                <Trophy className="w-4 h-4" />
                <span className="text-sm font-semibold matrix-font-secondary matrix-glow">{textContent.trophyText}</span>
                <Trophy className="w-4 h-4" />
              </div>

              <h1 className="text-4xl md:text-6xl font-black mb-8 leading-tight matrix-font-primary">
                {showFinalText ? (
                  <>
                    <span className="block text-white matrix-glow">{textContent.welcomeText}</span>
                    <span className="block matrix-final-text">
                      {textContent.companyName}
                    </span>
                  </>
                ) : (
                  <span className="block matrix-scramble whitespace-pre-line">
                    {matrixText}
                  </span>
                )}
              </h1>

              <p className="text-lg md:text-xl text-gray-300 mb-12 max-w-2xl mx-auto leading-relaxed matrix-font-secondary">
                {textContent.description}
              </p>

              {/* Stats Grid */}
              <div className="grid grid-cols-2 gap-8">
                {textContent.stats.map((stat, index) => (
                  <div className="text-center" key={index}>
                    <div className="text-2xl md:text-3xl font-bold text-yellow-400 mb-2 matrix-font-primary matrix-green-glow">{stat.value}</div>
                    <div className="text-gray-400 text-sm matrix-font-secondary">{stat.label}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Desktop Layout - Side by side */}
        <div className="hidden lg:grid lg:grid-cols-2 gap-16 items-center">
          
          {/* Left Column - Main Content */}
          <div className="text-center lg:text-left">
            <div className="inline-flex items-center gap-2 bg-gradient-to-r from-yellow-400/20 to-orange-500/20 border border-yellow-400/30 px-6 py-2 rounded-full text-yellow-400 mb-8 matrix-border">
              <Trophy className="w-4 h-4" />
              <span className="text-sm font-semibold matrix-font-secondary matrix-glow">{textContent.trophyText}</span>
              <Trophy className="w-4 h-4" />
            </div>

            <h1 className="text-4xl md:text-6xl lg:text-7xl font-black mb-8 leading-tight matrix-font-primary">
              {showFinalText ? (
                <>
                  <span className="block text-white matrix-glow">{textContent.welcomeText}</span>
                  <span className="block matrix-final-text">
                    {textContent.companyName}
                  </span>
                </>
              ) : (
                <span className="block matrix-scramble whitespace-pre-line">
                  {matrixText}
                </span>
              )}
            </h1>

            <p className="text-lg md:text-xl text-gray-300 mb-12 max-w-2xl mx-auto lg:mx-0 leading-relaxed matrix-font-secondary">
              {textContent.description}
            </p>

            {/* Stats Grid */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
              {textContent.stats.map((stat, index) => (
                <div className="text-center lg:text-left" key={index}>
                  <div className="text-2xl md:text-3xl font-bold text-yellow-400 mb-2 matrix-font-primary matrix-green-glow">{stat.value}</div>
                  <div className="text-gray-400 text-sm matrix-font-secondary">{stat.label}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Right Column - Video Section */}
          <VideoSection />

        </div>
      </div>
    </section>
  );
};

export default Hero;